"use client";
import { useEffect, useState } from "react";
import { Navbar } from "@/components/Navbar";
import { useWarmupSession } from "@/components/write/useWarmupSession";

type Cycle = { versions: { id:number; version:number; algorithmText:string; revisionReason:string|null; createdAt:string }[]; executions:{ id:number; versionId:number; result:string; problemLocation:string|null; executionNote:string; createdAt:string }[]; reflections:{ executionId:number; expectedMatch:string; problemLocation:string|null; cause:string; plannedRevision:string; createdAt:string }[] };
const resultLabel:Record<string,string>={success:"실행 성공",partial:"일부 수행 가능",impossible:"실행 불가능",wrong:"잘못된 결과"};

export default function ReflectPage(){
  const {checkingSession,loggedIn,studentLabel,mySubmission,handleLogout}=useWarmupSession();
  const [cycle,setCycle]=useState<Cycle|null>(null); const [expectedMatch,setExpectedMatch]=useState("no"); const [problemLocation,setProblemLocation]=useState(""); const [cause,setCause]=useState(""); const [plannedRevision,setPlannedRevision]=useState(""); const [error,setError]=useState<string|null>(null); const [busy,setBusy]=useState(false);
  useEffect(()=>{if(!mySubmission)return;fetch(`/api/warmup/research?submissionId=${mySubmission.id}`).then(r=>r.json()).then(setCycle).catch(()=>setError("기록을 불러오지 못했습니다."));},[mySubmission]);
  if(checkingSession)return <main className="p-10 text-center">불러오는 중...</main>;
  if(!loggedIn||!mySubmission)return <main className="p-10 text-center"><a className="text-blue-600 font-bold" href="/write">먼저 알고리즘을 작성하세요</a></main>;
  const latest=cycle?.versions.at(-1); const execution=cycle?.executions.filter(e=>e.versionId===latest?.id).at(-1); const reflected=execution&&cycle?.reflections.some(r=>r.executionId===execution.id);
  async function submit(e:React.FormEvent){e.preventDefault();if(!execution)return;setBusy(true);setError(null);const r=await fetch("/api/warmup/research",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"reflect",executionId:execution.id,expectedMatch,problemLocation,cause,plannedRevision})});const d=await r.json();setBusy(false);if(!r.ok){setError(d.error||"저장하지 못했습니다.");return;}location.reload();}
  return <div className="min-h-screen bg-slate-50"><Navbar currentStudentKey={studentLabel} onLogout={handleLogout}/><main className="mx-auto max-w-4xl p-4 sm:p-6 space-y-5">
    <header className="flex items-center justify-between"><div><span className="text-xs font-bold text-indigo-700">생각해보기</span><h1 className="text-xl font-black text-slate-900">실행 결과를 보고 내 알고리즘 점검하기</h1></div><a href="/write/algorithm" className="text-xs font-bold text-blue-700">← 작성 화면</a></header>
    <div className="grid gap-4 md:grid-cols-2"><section className="rounded-2xl border bg-white p-4 space-y-3"><h2 className="font-bold">버전 기록</h2>{cycle?.versions.map(v=><div key={v.id} className={`rounded-xl border p-3 ${v.id===latest?.id?"border-blue-300 bg-blue-50/40":"border-slate-200"}`}><div className="flex justify-between text-xs"><b>v{v.version}</b><span className="text-slate-400">{new Date(v.createdAt).toLocaleString("ko-KR")}</span></div><pre className="mt-2 whitespace-pre-wrap text-xs">{v.algorithmText}</pre>{v.revisionReason&&<p className="mt-2 border-t pt-2 text-xs text-indigo-700">수정 이유: {v.revisionReason}</p>}</div>)}</section>
    <section className="rounded-2xl border bg-white p-4 space-y-4"><h2 className="font-bold">현재 실행 결과</h2>{!execution?<div className="rounded-xl border border-dashed p-6 text-center text-sm text-slate-500">다른 학생의 실행 결과를 기다리고 있습니다.</div>:<><div className="rounded-xl bg-slate-50 p-3 text-sm space-y-1"><b>{resultLabel[execution.result]||execution.result}</b><p>문제 위치: {execution.problemLocation||"기록 없음"}</p><p>실행 기록: {execution.executionNote}</p></div>{reflected?<div className="rounded-xl bg-emerald-50 p-4 text-sm font-bold text-emerald-800">생각해보기를 완료했습니다. 이제 알고리즘을 수정해 새 버전으로 저장할 수 있습니다.<div><a href="/write/algorithm" className="mt-3 inline-block rounded-lg bg-emerald-700 px-4 py-2 text-white">알고리즘 수정하기 →</a></div></div>:<form onSubmit={submit} className="space-y-3"><label className="block text-xs font-bold">예상한 결과와 같았나요?<select value={expectedMatch} onChange={e=>setExpectedMatch(e.target.value)} className="mt-1 w-full rounded-xl border p-3"><option value="yes">예</option><option value="partial">일부 같음</option><option value="no">아니요</option></select></label><label className="block text-xs font-bold">문제가 발생한 부분<input value={problemLocation} onChange={e=>setProblemLocation(e.target.value)} className="mt-1 w-full rounded-xl border p-3"/></label><label className="block text-xs font-bold">문제의 원인은 무엇인가요?<textarea required value={cause} onChange={e=>setCause(e.target.value)} className="mt-1 w-full rounded-xl border p-3"/></label><label className="block text-xs font-bold">어떤 부분을 수정해야 하나요?<textarea required value={plannedRevision} onChange={e=>setPlannedRevision(e.target.value)} className="mt-1 w-full rounded-xl border p-3"/></label>{error&&<p className="text-xs text-rose-700">{error}</p>}<button disabled={busy} className="w-full rounded-xl bg-indigo-600 p-3 text-sm font-bold text-white">{busy?"저장 중...":"생각해보기 저장"}</button></form>}</>}</section></div>
    {cycle&&cycle.versions.length>1&&<section className="rounded-2xl border bg-white p-4"><h2 className="font-bold mb-3">초안과 현재 버전 비교</h2><div className="grid gap-3 md:grid-cols-2"><pre className="rounded-xl bg-slate-50 p-3 whitespace-pre-wrap text-xs"><b>v1 초안</b>{"\n\n"}{cycle.versions[0].algorithmText}</pre><pre className="rounded-xl bg-blue-50 p-3 whitespace-pre-wrap text-xs"><b>v{latest?.version} 현재</b>{"\n\n"}{latest?.algorithmText}</pre></div></section>}
  </main></div>;
}
